version: "3.3"
services:
  oracle:
    image: "switchboardlabs/node:dev-v2"
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - LIVE=1
      - CLUSTER=devnet
      - HEARTBEAT_INTERVAL=15 # Seconds
      - ORACLE_KEY=${ORACLE_KEY}
      # - RPC_URL=<YOUR CUSTOM SOLANA RPC ENTRYPOINT> # OPTIONAL
    volumes:
      - ./configs.json:/configs.json
secrets:
  PAYER_SECRETS:
    file: ./secrets/authority-keypair.json
