[package]
name = "on-chain-feed-parser"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
switchboard-aggregator = { version = "0.1.1" }
solana-program = "1.8.2"
anchor-lang = "0.18.0"

[lib]
crate-type = ["cdylib", "lib"]