[package]
name = "on-chain-feed-parser"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
switchboard-aggregator = { git = "https://github.com/gallynaut/switchboard-aggregator" }
solana-program = "1.8.2"

[lib]
crate-type = ["cdylib", "lib"]